services:
  # Frontend Web App
  - type: web
    name: blogs-frontend
    env: static
    buildCommand: cd web && npm install && npm run build
    staticPublishPath: web/build
    envVars:
      - key: REACT_APP_API_URL
        value: placeholder-api-url
      - key: REACT_APP_GEMINI_API_KEY
        value: placeholder-key
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    headers:
      - path: /*
        name: X-Frame-Options
        value: DENY
      - path: /*
        name: X-Content-Type-Options
        value: nosniff
      - path: /*
        name: Referrer-Policy
        value: strict-origin-when-cross-origin
      - path: /static/*
        name: Cache-Control
        value: public, max-age=31536000, immutable
